### ISSUE TITLE
ESP32 -HackRF portapack

### ISSUE THREAD

**Issue by Hackrfan** [htotoo/ESP32-Portapack#11]
hello totoo,
question : which map format is shown on your demo picture ( ADSB ) ( worldmap ) or your own?
If your own how do you do that? I still have problems.
Thanks and congratulations on your ESP32 portapack is very promising.
A picture of the hardware ( ESP32 / GPS ) with connection to the HackRF Portapak would be very helpful for a better understanding.
I am still a beginner

**Comment by htotoo** [comment]
Hello, that is the stock world map provided with pp.
Thank,. trying to add as may features as I can to make it  more useful.
Open for suggestions;)

If you want to create your own map there is a wiki page on the pp github.
