### ISSUE TITLE
flipper zero pocsag firmware corrupt

### ISSUE THREAD

**Issue by sysadminpower2019** [htotoo/ESP32-Portapack#12]
Hello when i use the pocsag pager with the hamradio network all i get is corrupted data. See screenshot. I'm not sure what to try
![pocsag](https://github.com/htotoo/ESP32-Portapack/assets/40726534/6abb19ff-9615-43d7-8e65-f9d50ae45fd7)

**Comment by htotoo** [comment]
Hello. This is not any Flipper's page, so I suggest to check what FW you use, and report the bug there after is is still exists after upgraded to the latest version.
For example Momentum fw page: https://github.com/Next-Flip/Momentum-Firmware
