### ISSUE TITLE
After burning, there is no WIFI signal. What is the reason? Do I need PP to transmit WIFI

### ISSUE THREAD

**Issue by WXLN** [htotoo/ESP32-Portapack#16]
![屏幕截图(53)](https://github.com/user-attachments/assets/62c2f259-3967-4ca1-afd0-d2939fb76b0c)

**Comment by htotoo** [comment]
You may have to wait for a bit before the AP shows up.  (max 2 min in the worst case)

You should check the logs. Plug it in computer (via the usb serial interface, not the otg one), and open the serial port it creates (com12 in your case). Then press reset, and copy here what it writes.

**Comment by htotoo** [comment]
Also try the new 0.9,3 edition, not the 0.8

**Comment by WXLN** [comment]
Later, I replaced it with an 8MB flash memory module, which was able to use the network normally, but the 4MB module still couldn't function properly
![Uploading MVIMG_20240915_182308.jpg…]()

**Comment by htotoo** [comment]
Yeah, the flash size designed to a minimum 16mb flash. So it is wonder it works with 8mb!
Don't try to update with ota,.it may break it.
